In [1]:
import zipfile

In [3]:
with zipfile.ZipFile('/content/healthcare_dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/healthcare_data')

In [4]:
import os
os.listdir('/content/healthcare_data')

['Final_Augmented_dataset_Diseases_and_Symptoms.csv']

In [6]:
import pandas as pd

df = pd.read_csv('/content/healthcare_data/Final_Augmented_dataset_Diseases_and_Symptoms.csv')
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0


In [7]:
df.shape

(246945, 378)

In [8]:
df['diseases'].unique()

array(['panic disorder', 'vocal cord polyp', 'turner syndrome',
       'cryptorchidism', 'poisoning due to ethylene glycol',
       'atrophic vaginitis', 'fracture of the hand',
       'cellulitis or abscess of mouth', 'eye alignment disorder',
       'headache after lumbar puncture', 'pyloric stenosis',
       'salivary gland disorder', 'osteochondrosis', 'injury to the knee',
       'metabolic disorder', 'vaginitis', 'sick sinus syndrome',
       'tinnitus of unknown cause', 'glaucoma', 'eating disorder',
       'transient ischemic attack', 'pyelonephritis',
       'rotator cuff injury', 'chronic pain disorder',
       'problem during pregnancy', 'liver cancer', 'atelectasis',
       'injury to the hand', 'choledocholithiasis', 'injury to the hip',
       'cirrhosis', 'thoracic aortic aneurysm', 'subdural hemorrhage',
       'diabetic retinopathy', 'fibromyalgia', 'ischemia of the bowel',
       'fetal alcohol syndrome', 'peritonitis', 'injury to the abdomen',
       'acute pancreati

In [9]:
df['diseases'].value_counts()

,count
diseases,
cystitis,1219
nose disorder,1218
vulvodynia,1218
complex regional pain syndrome,1217
spondylosis,1216
...,...
open wound of the head,1
myocarditis,1
chronic ulcer,1


In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['disease_encoded'] = le.fit_transform(df['diseases'])

In [11]:
df[['diseases','disease_encoded']].head()

,diseases,disease_encoded
0,panic disorder,531
1,panic disorder,531
2,panic disorder,531
3,panic disorder,531
4,panic disorder,531


In [12]:
X = df.drop(['diseases','disease_encoded'], axis=1)
y = df['disease_encoded']

In [13]:
X.head()

,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,palpitations,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,1,0,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [18]:
model.score(X_test, y_test)

0.8644839944117111

In [19]:
sample = X_test.iloc[:1]
sample

,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,palpitations,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
94355,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [20]:
prediction = model.predict(sample)
prediction

array([621])

In [21]:
le.inverse_transform(prediction)

array(['retinal detachment'], dtype=object)

In [22]:
y_test.iloc[:1]

,disease_encoded
94355,121


In [23]:
le.inverse_transform(y_test.iloc[:1])

array(['chronic glaucoma'], dtype=object)

In [24]:
predictions = model.predict(X_test.iloc[:10])
le.inverse_transform(predictions)

array(['retinal detachment', 'torticollis', 'schizophrenia',
       'fracture of the patella', 'chronic otitis media', 'arrhythmia',
       'chronic otitis media', 'multiple sclerosis', 'neuralgia',
       'hyperkalemia'], dtype=object)

In [25]:
le.inverse_transform(y_test.iloc[:10])

array(['chronic glaucoma', 'torticollis', 'personality disorder',
       'fracture of the patella', 'chronic otitis media', 'arrhythmia',
       'chronic otitis media', 'peripheral nerve disorder', 'neuralgia',
       'hyperkalemia'], dtype=object)

In [26]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        20
           1       0.95      0.94      0.94        81
           2       0.60      0.91      0.73        58
           3       1.00      1.00      1.00         6
           4       0.95      0.94      0.94        63
           5       0.75      1.00      0.86         6
           6       0.42      1.00      0.59         5
           7       0.65      1.00      0.78        20
           8       0.60      0.91      0.73       103
           9       0.93      0.78      0.85       179
          10       1.00      0.89      0.94       253
          11       0.98      0.63      0.77       221
          12       0.74      0.78      0.76       187
          13       0.43      1.00      0.60         3
          14       0.45      0.55      0.49        31
          15       1.00      0.96      0.98       209
          16       0.72      0.93      0.81       145
          17       1.00    

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [28]:
model.predict_proba(X_test.iloc[:5])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB

scores = cross_val_score(GaussianNB(), X, y, cv=5)
scores

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.86393731, 0.8679868 , 0.86729839, 0.86735913, 0.86420053])

In [31]:
scores.mean()

np.float64(0.8661564315940797)

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB

clf = Pipeline([
    ('nb', GaussianNB())
])

In [33]:
clf.fit(X_train, y_train)

Pipeline(steps=[('nb', GaussianNB())])

In [34]:
clf.score(X_test, y_test)

0.8644839944117111

In [35]:
pred = clf.predict(X_test.iloc[:5])
le.inverse_transform(pred)

array(['retinal detachment', 'torticollis', 'schizophrenia',
       'fracture of the patella', 'chronic otitis media'], dtype=object)

In [37]:
df.isnull().sum()

,0
diseases,0
anxiety and nervousness,0
depression,0
shortness of breath,0
depressive or psychotic symptoms,0
...,...
back swelling,0
ankle stiffness or tightness,0
ankle weakness,0
neck weakness,0


In [38]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB

clf = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('nb', GaussianNB())
])

In [39]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8644839944117111

In [40]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm

array([[ 20,   0,   0, ...,   0,   0,   0],
       [  0,  76,   0, ...,   0,   0,   0],
       [  0,   0,  53, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   1,   0,   0],
       [  0,   0,   0, ...,   0, 102,   0],
       [  0,   0,   0, ...,   0,   0,   2]])